# **00.PyTorch Fundamentals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## **Introduction to Tensors**
### **creating tensors**

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
# Check the number of dimensions of scalar
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
#Matrix
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check number of dimensions
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
#tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
# Check number of dimensions
tensor.ndim

3

In [16]:
# Check shape of TENSOR
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensor

In [18]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1166, 0.5117, 0.6924, 0.2789],
        [0.8327, 0.4987, 0.1797, 0.7849],
        [0.6059, 0.4920, 0.6597, 0.4048]])

In [19]:
random_tensor.ndim

2

In [20]:
#create a random tensor of size (224,224,3)
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,weight,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### **Zeros and ones**

In [21]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

### **Creating a range of tensors and tensors_like**

In [26]:
#Use torch.range()
torch.range(0,10)

<ipython-input-26-22d360b9a54e>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
torch.__version__

'2.3.0+cu121'

In [29]:
tensor=torch.arange(start=1,end=1000,step=100)
tensor

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [30]:
#Can also create a tensor of zeros similar to another tensor
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes
**Note**:Tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning


1.   Tensors not right datatype
2.   Tensors not right shape

1.   Tensors not on the right device







In [31]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                             device=None,# defaults to None, which uses the default tensor type
                             requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.shape

(torch.float32, device(type='cpu'), torch.Size([3]))

In [32]:
#float 16 tensor
float_16_tensor=torch.HalfTensor([3.0,6.0,9.0])
float_16_tensor.dtype

torch.float16

In [33]:
#--or--
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [34]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor=torch.tensor([3,6,9],
                           dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

##Getting information from tensor

1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor, can use tensor.shape

3.Tensors not on the right device - to get device from a tensor, can use tensor.device

In [37]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.7681, 0.0457, 0.3793, 0.3428],
        [0.7109, 0.7277, 0.5813, 0.7452],
        [0.9876, 0.7502, 0.5048, 0.7667]])

In [38]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7681, 0.0457, 0.3793, 0.3428],
        [0.7109, 0.7277, 0.5813, 0.7452],
        [0.9876, 0.7502, 0.5048, 0.7667]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [39]:
print(f"Size of tensor: {some_tensor.size()}")

Size of tensor: torch.Size([3, 4])


## Manipulating Tensor(tensor operations)

Tensor operations include:
* addition
* subtraction
* multiplication (element-wize)
* division
*matrix multiplication

In [40]:
#create a tensor and add 10 to it
tensor=torch.tensor([10,11,12])
tensor+10

tensor([20, 21, 22])

In [41]:
#multiply tensor by 10
tensor*10

tensor([100, 110, 120])

In [42]:
#subtract 10
tensor-10

tensor([0, 1, 2])

In [43]:
#can also use torch fn
torch.mul(tensor,10)

tensor([100, 110, 120])

## Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1.Element-wise multiplication

2.Matrix multiplication (dot product)

In [44]:
#Element wise multiplication
tensor

tensor([10, 11, 12])

In [45]:
tensor*tensor

tensor([100, 121, 144])

In [46]:
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 11, 12]) * tensor([10, 11, 12])
Equals: tensor([100, 121, 144])


In [47]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(365)

In [48]:
#Matrix muliplication by hand
10*10 + 11*11 + 12*12

365

In [49]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 1.94 ms, sys: 0 ns, total: 1.94 ms
Wall time: 2.61 ms


tensor(365)

In [50]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.49 ms, sys: 0 ns, total: 1.49 ms
Wall time: 1.94 ms


tensor(365)

In [51]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
%%time
tensor@tensor

CPU times: user 1.68 ms, sys: 111 µs, total: 1.79 ms
Wall time: 2.83 ms


tensor(365)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

###One of the most common error in deep learning: shape errors

In [52]:
#shape for matrik multiplication
tensor_a=torch.tensor([[1,2],
                       [2,3],
                       [3,4]],dtype=torch.float32)
tensor_b=torch.tensor([[4,5],
                       [5,6],
                       [6,7]],dtype=torch.float32)
#torch.mm(tensor_a,tensor_b)
torch.matmul(tensor_a,tensor_b) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [53]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**

A **transpose** switches the axes or dimensions of a gn tensor

In [54]:
tensor_b.T, tensor_b

(tensor([[4., 5., 6.],
         [5., 6., 7.]]),
 tensor([[4., 5.],
         [5., 6.],
         [6., 7.]]))

In [55]:
torch.mm(tensor_a,tensor_b.T)

tensor([[14., 17., 20.],
        [23., 28., 33.],
        [32., 39., 46.]])

In [56]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[14., 17., 20.],
        [23., 28., 33.],
        [32., 39., 46.]])

##Finding the min,max,sum,etc(tensor aggregation)

In [57]:
#create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
#find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [59]:
#find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [60]:
#find the mean-note: the torch.mean() fn requies a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
#Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

###Finding the positional min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
x.argmin()

tensor(0)

In [64]:
x.argmax()

tensor(9)

##Reshaping,stacking,squeezing,unsqueezing tensors

* Reshaping-reshapes an i/p tensor to a defined shape.

* View-Return a view of an i/p tensor of certain shape but keep the same memory as the original tensor

* Stacking- combine multiple tensors on top of each other(vstack) or side by side (hstack)

* Squeeze- removes all `1` dim from a tensor

* Unsqueeze- add a `1`dim to a target tensor

* Permute-Return a view of the i/p with dims permuted(swapped) in a certain way


In [65]:
#let's create a tensor
x=torch.arange(1.0,9.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [66]:
#add a extra dim
x_reshaped=x.reshape(2,4)
x_reshaped

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [67]:
#change the view
z=x.view(2, 4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [68]:
#changing z changes x (because a view of a tensor shares the same memory as the original shape)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8.]))

In [72]:
#stack tensors on top of each other-hstack
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.]])

In [73]:
#vstack
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [74]:
#torch.squeeze()-removes all single dims from a target tensor
x_reshaped

tensor([[5., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [75]:
x_reshaped.shape

torch.Size([2, 4])

In [76]:
x_reshaped.squeeze()

tensor([[5., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [77]:
x_reshaped.squeeze().shape

torch.Size([2, 4])

In [78]:
x_reshaped=x_reshaped.reshape(8,1)
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])

In [79]:
x_reshaped.shape

torch.Size([8, 1])

In [80]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8.])

In [81]:
x_reshaped.squeeze().shape

torch.Size([8])

In [82]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])
Previous shape: torch.Size([8, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])


In [83]:
#torch.unsqueeze()-add a single dims to a target tensor at a specific dims
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add a extra dim with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])

New shape: torch.Size([1, 8])


In [84]:
#torch-permute-rearranges the dims of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3)) #[height,width,colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [85]:
x_original[0,0,0]=722000
x_original[0,0,0],x_permuted[0,0,0]

(tensor(722000.), tensor(722000.))

## Indexing (selection data from tensors)

Indexing with Pytorch is similar to indexing with numpy

In [86]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
#let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
#let's index on our middle bracket(dim=1)
x[0][0]
#--or
#x[0,0]

tensor([1, 2, 3])

In [89]:
#let's index on the most inner bracket(last dims)
x[0][0][0]
#--or
#x[0,0,0]

tensor(1)

In [90]:
x[0,1,1]

tensor(5)

In [91]:
x[0,2,2]

tensor(9)

In [92]:
#you can also use ":" to select "all" of a target dim
x[:,0]

tensor([[1, 2, 3]])

In [93]:
x[:,0,2]

tensor([3])

In [94]:
#Get all values of 0th and 1st dims but only index 1 and 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [95]:
x[:,:,2]

tensor([[3, 6, 9]])

In [96]:
#get all values of the 0 dim but only the 1 index valueof 1st and 2nd dim
x[:,0,0]

tensor([1])

In [97]:
#get index 0 of 0th and 1st dims and all values of 2nd dim
x[0:,0,:]

tensor([[1, 2, 3]])

In [98]:
#Index on x to 9
print(x[:,2:,2])
#print(x[0][2][2])

#index on x to return 3,6,9
print(x[:,:,2])

tensor([[9]])
tensor([[3, 6, 9]])


##Pytorch tensor & Numpy
Numpy is a popular scientific Python numerical computing library.
and because of this,Pytorch has functionality to interact with it.
* Data in Numpy, want in pytorch tensor-> `torch.from_numpy(ndarray)`
* PyTorch tensor->Numpy->`torch.Tensor.numpy()`

In [104]:
#Numpy array to tensor
array=np.arange(1.0,10.0)
tensor=torch.from_numpy(array)#warning: when converting from numpy->pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [101]:
array.dtype

dtype('float64')

In [102]:
tensor.dtype

torch.float64

In [103]:
torch.arange(1.0,10.0).dtype

torch.float32

In [105]:
#change the value of array, what will this do to `tensor`?
array=array+1
array,tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [110]:
#tensor to Numpy array
tensor=torch.arange(1.0,10.0)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [111]:
tensor.dtype

torch.float32

In [112]:
#change the tensor,what happens to `numpy_tensor`?
tensor= tensor+1
tensor,numpy_tensor

(tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

##Reproducbility(trying to take random out of random)
In short how a neural network learns:

`start with random numbers-> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again...`

To reduce the randomness in neural networks and pyTorch comes the concept of a **random seed.**

Essentially what the random seed does is "flavour" the randomness.

In [117]:
torch.rand(3,3)

tensor([[0.8464, 0.2162, 0.9449],
        [0.4822, 0.6606, 0.6660],
        [0.5411, 0.7811, 0.3128]])

In [118]:
#create a new random tensors
random_tensor_a=torch.rand(3,5)
random_tensor_b=torch.rand(3,5)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.7631, 0.2959, 0.7503, 0.1041, 0.4888],
        [0.2421, 0.9190, 0.4094, 0.0553, 0.1484],
        [0.5942, 0.5666, 0.7479, 0.9056, 0.6600]])
tensor([[0.9760, 0.1194, 0.9338, 0.0583, 0.0546],
        [0.3134, 0.1017, 0.7173, 0.3281, 0.9358],
        [0.8951, 0.3707, 0.8260, 0.4684, 0.2549]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [121]:
#Let's make some random but reproduciable tensor
#set the random seed
Random_seed=42
torch.manual_seed(Random_seed)
random_tensor_c=torch.rand(3,5)

torch.manual_seed(Random_seed)
random_tensor_d=torch.rand(3,5)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs(and making faster computations)

GPUs=faster computation on numbers, thanks to CUDA+NVIDIA hardware+Pytorch working behind the scenes to make everything hunky dory(good)

###Getting a GPU
1. Easiest-Use Google Colab for a free GPU(options to upgrade as well)
2. Use your own GPU-takes a little bit setup and requires the investment of purchasing a GPU,there's lots of options...,
3.Use cloud computing-GCP,AWS,Azure these services allow you to rent computers on the cloud and access them

In [1]:
!nvidia-smi

Fri May 31 06:58:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

###Check for GPU access with pytorch

In [2]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [3]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
#Count no of devices(GPU)
torch.cuda.device_count()

1

In [8]:
# Check for Apple Silicon GPU - In order to run PyTorch on Apple's M1/M2/M3 GPUs you can use the torch.backends.mps module.
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running

False

In [7]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [11]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

device

'cuda'

##Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.


In [12]:
#create a tensor(default on the CPU)
tensor=torch.tensor([1,2,3,4])

#Tensor not a GPU
print(tensor,tensor.device)

tensor([1, 2, 3, 4]) cpu


In [14]:
#move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu,tensor_on_gpu.device

(tensor([1, 2, 3, 4], device='cuda:0'), device(type='cuda', index=0))

###Moving tensor back to the CPU

In [16]:
#If tensor is on GPU,can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [19]:
#To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3, 4])

In [20]:
tensor_on_gpu

tensor([1, 2, 3, 4], device='cuda:0')